### ISSUE TITLE
[FEATURE] where are the SEMS APIs documented?

### ISSUE THREAD

**Issue by AaronSaikovski** [andrewgierens/sems_portal_api#7]
Hi there,
not really a feature request but more of a question.
I was after any developer documentation on where the SEMS APIs were documented and if you had any information you could share?
thanks!

**Comment by andrewgierens** [comment]
Hi mate, there isn't any official documentation as these are just using the apis that their website uses - Not 100% sure they actually support this

Was just trial and error by inspecting their web requests

**Comment by AaronSaikovski** [comment]
thanks looks like ill do the same...not great documentation available
